#pragma once

// menu
#define MENU_BG								"Resources/game_menu/background.bmp"
#define INS									"Resources/game_menu/ins/ins.bmp"
#define BUTTON_PLAY							"Resources/game_menu/button/play.bmp"
#define BUTTON_PLAY_CLICKED					"Resources/game_menu/button/play_clicked.bmp"
#define BUTTON_INS							"Resources/game_menu/button/instructions.bmp"
#define BUTTON_INS_CLICKED 		   			"Resources/game_menu/button/instructions_clicked.bmp"
#define BUTTON_OK_CLICKED			   		"Resources/game_menu/button/ok_clicked.bmp"
// select page
#define SELECT_PAGE_BG						"Resources/game_run/select_page/level_bg.bmp"
#define SELECT_PAGE_DIAMOND_BLUE			"Resources/game_run/select_page/blue_diamond.bmp"
#define SELECT_PAGE_DIAMOND_BLUE_CLICKED	"Resources/game_run/select_page/blue_diamond_clicked.bmp"
#define SELECT_PAGE_DIAMOND_ORANGE			"Resources/game_run/select_page/orange_diamond.bmp"
#define SELECT_PAGE_DIAMOND_ORANGE_CLICKED	"Resources/game_run/select_page/orange_diamond_clicked.bmp"
#define SELECT_PAGE_DIAMOND_GREEN			"Resources/game_run/select_page/green_diamond.bmp"
#define SELECT_PAGE_DIAMOND_GREEN_CLICKED	"Resources/game_run/select_page/green_diamond_clicked.bmp"

#define BOY_STOP							"Resources/game_run/person/boy/boy_stop.bmp"
#define BOY_RIGHT_1							"Resources/game_run/person/boy/right/r1.bmp"
#define BOY_RIGHT_2							"Resources/game_run/person/boy/right/r3.bmp"
#define BOY_RIGHT_3							"Resources/game_run/person/boy/right/r5.bmp"
#define BOY_RIGHT_4							"Resources/game_run/person/boy/right/r7.bmp"
#define BOY_LEFT_1							"Resources/game_run/person/boy/left/l1.bmp"
#define BOY_LEFT_2							"Resources/game_run/person/boy/left/l3.bmp"
#define BOY_LEFT_3							"Resources/game_run/person/boy/left/l5.bmp"
#define BOY_LEFT_4							"Resources/game_run/person/boy/left/l7.bmp"
#define GIRL_STOP							"Resources/game_run/person/girl/girl_stop.bmp"
#define GIRL_RIGHT_1						"Resources/game_run/person/girl/right/r1.bmp"
#define GIRL_RIGHT_2						"Resources/game_run/person/girl/right/r3.bmp"
#define GIRL_RIGHT_3						"Resources/game_run/person/girl/right/r5.bmp"
#define GIRL_RIGHT_4						"Resources/game_run/person/girl/right/r7.bmp"
#define GIRL_LEFT_1							"Resources/game_run/person/girl/left/l1.bmp"
#define GIRL_LEFT_2							"Resources/game_run/person/girl/left/l3.bmp"
#define GIRL_LEFT_3							"Resources/game_run/person/girl/left/l5.bmp"
#define GIRL_LEFT_4							"Resources/game_run/person/girl/left/l7.bmp"
#define LEVEL_1_BG							"Resources/game_run/map/map_background/map1.bmp"
#define MAP_TEMPLATE						"Resources/game_run/map/.map/map1.map"
#define DIAMOND_RED_1						"Resources/game_run/diamond/red/red_1.bmp"
#define DIAMOND_RED_2						"Resources/game_run/diamond/red/red_2.bmp"
#define DIAMOND_BLUE_1						"Resources/game_run/diamond/blue/blue1.bmp"
#define DIAMOND_BLUE_2						"Resources/game_run/diamond/blue/blue2.bmp"
#define PURPLE_BUTTON						"Resources/game_run/button/button_purple.bmp"
#define PURPLE_PLAT							"Resources/game_run/platform/platform_purple.bmp"
#define YELLOW_PLAT							"Resources/game_run/platform/platform_yellow.bmp"
#define SWITCH_RIGHT						"Resources/game_run/switch/switch_right.bmp"
#define SWITCH_LEFT							"Resources/game_run/switch/switch.left.bmp"
